#!/usr/bin/python
import sys
import os

def usage():
    print """

  openbazaar - A decentralized marketplace for instantly trading with anyone 
               using Bitcoin.

  Usage: openbazaar <command>

  COMMANDS:
  start     

  stop

  restart

  """

def main(argv):
    if len(argv) >= 2:
        COMMANDS = {'start':'/usr/share/openbazaar/run.sh',
                    'stop':'/usr/share/openbazaar/stop.sh',
                    'restart':'/usr/share/openbazaar/stop.sh; /usr/share/openbazaar/run.sh'}
        try:
            command = argv[1]
            if command in COMMANDS:
                os.chdir('/usr/share/openbazaar')
                os.system(COMMANDS[command])
            else:
                usage()
        except Exception:
            usage()
    else:
        usage()


if __name__=='__main__':
    main(sys.argv)
