#!/bin/bash
set -e
echo "[openbazaar] Installing OpenBazaar python dependencies..."
pushd /usr/share/openbazaar
sudo pip install -r requirements.txt

pushd pysqlcipher
sudo python setup.py install
popd
popd

sudo chmod -R 775 /usr/share/openbazaar
sudo chown -R $SUDO_USER:$SUDO_USER /usr/share/openbazaar

echo
echo
echo
echo
echo "[openbazaar] Installation finished."
echo "[openbazaar] Now type 'openbazaar start' to start OpenBazaar"
echo "[openbazaar] then open 'http://localhost:8888' with your favorite web browser"
echo
echo
echo
echo
