.TH OPENBAZAAR 1 "Aug 27, 2014" "version 0.1.0"
.SH NAME
openbazaar \- OpenBazaar (Decentralized p2p marketplace)
.SH SYNOPSIS
.B openbazaar
.SH DESCRIPTION

\fBOpenBazaar\fB is an open source project to create a decentralized
network for commerce online (using Bitcoin) that has no fees and
cannot be censored.

.SH SEE ALSO
For more information on the usage of the program visit
http://www.openbazaar.org

openbazaar homepage: http://www.openbazaar.org
.SH AUTHOR
OpenBazaar is written by the OpenBazaar Team <project@openbazaar.org>

This manual page was written by Angel Leon <gubatron@openbazaar.org>
